name: PDK
on: [ push ]
jobs:
  debug:
    runs-on: ubuntu-latest
    container: puppet/pdk:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: run pdk validate
        run: |
          ls -lah
          pdk --version --debug
  validate:
    runs-on: ubuntu-latest
    container: puppet/pdk:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: run pdk validate
        run: pdk validate --format=text --debug
  # unit-test:
  #   runs-on: ubuntu-latest
  #   container: puppet/pdk:latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - name: run pdk test unit
  #       run: pdk test unit --format=text
